### PR TITLE
fix broken otto dev

### PR DESCRIPTION
**Pull request by gotcha**
With current otto code, virtualenv 13.1.2 only installs `virtualenv` and `virtualenv-3.4` :-S, no `virtualenv-2.7`

### CODE REVIEW

**Comment by gotcha** [comment]
I see you have merged upstream.

I will make a new pull request without upstream.

**Comment by jmetzmeier** [comment]
Thanks for the pull request. Since this a simple fix, I am going to go ahead and insert it manually. The fix also needs to be applied to build-python.sh, which contains the same bad line.

**Comment by jmetzmeier** [comment]
Actually, I will wait a bit for the new PR so your name is on the commit, since you did the work.

**Comment by gotcha** [comment]
Any idea why bindata has to be checked in rather than git ignored ?

I am a go newbie.

**Comment by gotcha** [comment]
`bindata.go` should not be in the repo : see https://github.com/jmetzmeier/otto/commit/ec8997ebce5afdcb1a4ae189efbd385993b19b3f

**Comment by jmetzmeier** [comment]
That makes sense, I will remove it from the branch.

**Comment by gotcha** [comment]
@jmetzmeier lemme do it

**Comment by gotcha** [comment]
already done here and I will need to kill all git changes again :-S

**Comment by jmetzmeier** [comment]
Whoops. I will stop pushing stuff now :).

**Comment by gotcha** [comment]
too late, you did it :-)

Yes please

**Pull request closed without merging**
